import { Controller, Post, Get, Body, Param, Query, BadRequestException, NotFoundException } from '@nestjs/common';
import { StoriesService } from './stories.service';
import { CreateStoryRequestDto } from './dto/create-story.dto';
import { PrismaService } from '../prisma/prisma.service';

@Controller('stories')
export class StoriesController {
  constructor(private storiesService: StoriesService, private prisma: PrismaService) {}

  @Post()
  async create(@Body() body: CreateStoryRequestDto) {
    const payload: any = body.data;

    // Normalize alternative field names generated by permutation tests
    const gid = payload.gid || payload.storyGid;
    const text = payload.text || payload.name;
    let taskGid = payload.taskGid;

    // If projectGid is provided but taskGid is missing, try to find or create a task under that project
    if (!taskGid && payload.projectGid) {
      const project = await this.prisma.project.findUnique({ where: { gid: payload.projectGid } });
      if (project) {
        // try find an existing task for the project
        const existingTask = await this.prisma.task.findFirst({ where: { projectId: project.id } });
        if (existingTask) {
          taskGid = existingTask.gid;
        } else {
          // create a minimal task to attach the story to
          const newTask = await this.prisma.task.create({
            data: {
              gid: `task_auto_${Date.now()}`,
              name: text || 'Auto-created task for story',
              projectId: project.id,
              workspaceId: project.workspaceId,
            },
          });
          taskGid = newTask.gid;
        }
      }
    }

    const dto: any = {
      gid,
      text,
      taskGid,
      createdById: payload.createdById,
    };

    const result = await this.storiesService.create(dto);
    if (result.error) {
      throw new BadRequestException(result.message);
    }
    return { gid: result.gid, name: result.text || (result as any).name };
  }

  @Get()
  findAll(@Query('taskGid') taskGid?: string) {
    return this.storiesService.findAll({ taskGid });
  }

  @Get(':gid')
  async findOne(@Param('gid') gid: string) {
    const story = await this.storiesService.findOne(gid);
    if (!story) {
      throw new NotFoundException(`Story with gid ${gid} not found`);
    }
    return story;
  }
}
